version: "3.8"
services:
  redis:
    image: redis:4
    restart: always
    container_name: cache
    ports:
      - 6379:6379

  app:
    depends_on:
      - redis
    links:
      - redis
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://cache
    command: sh -c 'npm ci && node index.js'
